title: Personal blog
author: Sajan Kasula
email: sajankasula@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi I am here to introduce me as a newbie programmer. Still learning making mistakes.

# social links
twitter_username: sazan-kasula # DO NOT include the @ character, or else the build will fail!
github_username:  Sajan390 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
